import flet as ft
import webbrowser # Flet UI library

class CompanyDashboard:
    def __init__(self, ticket, country, exchange, currency, name, description, official_site, table_data, summary, logo_url=None):
        """Initialize the dashboard with all needed company data.
        
        :param ticket: Ticket in the Stock Market
        :param country: Country of the company
        :param exchange: Stock Market Exchange of the company
        :param currency: Currency of the action
        :param name: Name of the company
        :param description: Brief description of the company
        :param table_data: A dictionary with 'columns' and 'rows' for the financial table
        :param summary: AI-generated analysis
        :param logo_url: URL to the company's logo image
        """
       
        self.ticket = ticket 
        self.country = country 
        self.exchange = exchange
        self.currency = currency
        self.name = name
        self.description = description
        self.official_site = official_site
        self.table_data = table_data
        self.summary = summary
        self.logo_url = logo_url

    def render(self):
        """Build and return the dashboard UI as a Flet component (Card)"""

        # Create the financial data table
        table = ft.DataTable(
            columns=[ft.DataColumn(ft.Text(col, size=12)) for col in self.table_data["columns"]],
            rows=[
                ft.DataRow(
                    cells=[
                        ft.DataCell(ft.Text(str(cell), size=12)) for cell in row
                    ]
                )
                for row in self.table_data["rows"]
            ],
            
        )


        # Return the full card layout
        return ft.Card(
            content=ft.Container(
                content=ft.Column([

                    # Header with logo and name
                    ft.Row([
                        ft.Image(src=self.logo_url, width=50) if self.logo_url else ft.Container(),
                        ft.Text(self.name, size=20, weight=ft.FontWeight.BOLD)
                    ]),

                     #Ticket Stock Market
                    ft.Row([
                        ft.Text(self.country, size=18, weight=ft.FontWeight.BOLD),
                        ft.Text(self.exchange, size=18, weight=ft.FontWeight.BOLD),
                        ft.Text(self.ticket, size=18, weight=ft.FontWeight.BOLD)
                    ], alignment=ft.MainAxisAlignment.END),  # <-- Alineación derecha


                    # Company description
                    ft.Text(self.description, size=13),

                    ft.ElevatedButton(
                        text="Go to Site", 
                        on_click=lambda e: webbrowser.open(self.official_site)
                    ),

                    ft.Divider(),

                    # Financial data table section
                    ft.Text("Financial Data", size=16, weight=ft.FontWeight.W_600),
                    table,
                    ft.Divider(),

                    # Summary/analysis
                    ft.Text(self.summary, italic=True, size=12)
                ]),
                padding=20,
                bgcolor=ft.colors.SURFACE_VARIANT,
                border_radius=12
            )
        )

def main(page: ft.Page):
    page.scroll = ft.ScrollMode.AUTO 
    # Example usage
    dashboard = CompanyDashboard(
        country="USA",
        exchange="NYSE", 
        currency="USD",
        ticket="IBM",
        name="International Business Machines",
        description="International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
        official_site="www.ibm.com",
        table_data={
            "columns":  ["Metric", "2024", "2023", "2022"],  # o "Current", "Previous", etc.

            "rows": [
                    
                                    # INCOME STATEMENT
                        ["Annual Revenue", "$36.016.000.000", "$31.496.000.000", "$29.870.000.000"],
                        ["Gross Profit", "$13.764.000.000", "$11.312.000.000", "$10.420.000.000"],
                        ["Operating Income", "$5.502.000.000", "$3.534.000.000", "$2.900.000.000"],
                        ["Net Income Attributable to Shareholders", "$4.959.000.000", "$2.717.000.000", "$2.300.000.000"],

                        # MARGINS
                        ["Gross Margin", "38,22%", "36,50%", "35,10%"],
                        ["Operating Margin", "15,28%", "11,22%", "9,70%"],
                        ["Net Margin", "13,77%", "8,63%", "7,70%"],

                        # BALANCE SHEET
                        ["Cash", "$1.810.000.000", "$1.500.000.000", "$1.300.000.000"],
                        ["Financial Liabilities (Debt)", "$18.988.000.000", "$20.200.000.000", "$21.000.000.000"],
                        ["Current Assets", "$11.703.000.000", "$10.900.000.000", "$10.200.000.000"],
                        ["Current Liabilities", "$19.013.000.000", "$18.000.000.000", "$17.500.000.000"],
                        ["Total Assets", "$71.391.000.000", "$68.000.000.000", "$65.000.000.000"],
                        ["Total Liabilities", "$43.025.000.000", "$41.000.000.000", "$39.000.000.000"],
                        ["Shareholders' Equity", "$28.366.000.000", "$26.920.000.000", "$26.000.000.000"],

                        # FINANCIAL RATIOS
                        ["Equity Growth %", "5,37%", "3,54%", "2,90%"],
                        ["Current Ratio", "0,62", "0,61", "0,58"],
                        ["Acid-Test Ratio", "0,10", "0,12", "0,11"],
                        ["Total Assets / Total Liabilities", "1,66", "1,66", "1,67"],
                        ["Cash Percentage", "6,38%", "6,25%", "6,00%"],
                        ["Debt Ratio", "66,94%", "67,25%", "68,00%"],
                        ["Return on Assets (ROA)", "6,95%", "4,00%", "3,50%"],
                        ["Return on Equity (ROE)", "17,48%", "10,10%", "9,30%"],

                        # STOCK DATA
                        ["Shares Outstanding", "1.290.000.000", "1.300.000.000", "1.320.000.000"],
                        ["Stock Price", "$71,61", "$69,20", "$65,00"],
                        ["Market Capitalization", "$92.376.900.000", "$89.960.000.000", "$85.800.000.000"],
                        ["Earnings Per Share (EPS)", "$3,84", "$2,80", "$2,30"],
                        ["Price / Earnings (P/E)", "18,63", "24,71", "28,26"],
                        ["Book Value Per Share", "$21,99", "$20,80", "$20,10"],
                        ["Price / Book Value (P/BV)", "3,26", "3,33", "3,23"],
                        ["Revenue Per Share", "$27,92", "$24,50", "$22,63"],
                        ["Price / Sales", "2,56", "2,82", "2,87"],
                        ["Annual Dividend", "$1,62", "$1,58", "$1,52"],
                        ["Dividend Yield", "2,26%", "2,28%", "2,34%"]
                                    
                ]

            
        },
        summary="Analysis with RAG",
        logo_url="https://logo.clearbit.com/ibm.com"
    )

    # Add the dashboard to the page
    page.add(dashboard.render())

# Run the app
ft.app(target=main)
